# Generated by Django 2.1 on 2019-11-20 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBookShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='图书名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('download', models.URLField(blank=True, max_length=100, verbose_name='下载地址')),
            ],
        ),
        migrations.CreateModel(
            name='MyKnowledgeUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='资料名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('search_url', models.URLField(blank=True, max_length=100, verbose_name='资料链接')),
            ],
        ),
    ]
