# Generated by Django 2.1 on 2019-11-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybookshare',
            options={'verbose_name': '图书分享', 'verbose_name_plural': '图书分享列表'},
        ),
        migrations.AlterModelOptions(
            name='myknowledgeurl',
            options={'verbose_name': '网站分享', 'verbose_name_plural': '网站资料列表'},
        ),
    ]
