# Generated by Django 2.1 on 2019-11-20 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20191120_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='图书名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('download', models.URLField(blank=True, max_length=100, verbose_name='下载地址')),
            ],
            options={
                'verbose_name': '软件分享',
                'verbose_name_plural': '软件分享列表',
            },
        ),
    ]
