# Generated by Django 2.1 on 2019-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_mysoftware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysoftware',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='软件名称'),
        ),
    ]
