# Generated by Django 2.1 on 2019-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='称呼')),
                ('friend_url', models.URLField(verbose_name='链接地址')),
                ('website_name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('your_email', models.EmailField(max_length=254, verbose_name='友链接邮箱')),
                ('url_image', models.ImageField(upload_to='friend_photo/%Y%m%d/', verbose_name='链接图片')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['submit_time'],
            },
        ),
    ]
