# Generated by Django 2.1 on 2019-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='url_image',
            field=models.ImageField(upload_to='link/%Y%m%d/', verbose_name='链接图片'),
        ),
    ]
