# Generated by Django 2.1 on 2019-11-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_link', '0002_auto_20191108_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='url_image',
            field=models.ImageField(blank=True, upload_to='link/%Y%m%d/', verbose_name='链接图片'),
        ),
    ]
