# Generated by Django 2.1 on 2019-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_link', '0003_auto_20191113_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='url_image',
            field=models.ImageField(blank=True, upload_to='link/%Y%m%d/', verbose_name='网站代表图片'),
        ),
        migrations.AlterField(
            model_name='friendlink',
            name='your_email',
            field=models.EmailField(max_length=254, verbose_name='友情链接邮箱(为您保密)'),
        ),
    ]
