# Generated by Django 2.1 on 2019-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_line_photo', models.ImageField(blank=True, null=True, upload_to='story_line_photo', verbose_name='故事时间线图片')),
                ('story_title', models.TextField(verbose_name='故事标题')),
                ('story_text', models.TextField(verbose_name='事件简要说明')),
                ('story_time', models.DateTimeField(verbose_name='故事事件')),
            ],
            options={
                'verbose_name': '大事件',
                'verbose_name_plural': '大事件',
            },
        ),
    ]
