# Generated by Django 2.1 on 2019-11-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='development',
            options={'verbose_name': '网站更新内容', 'verbose_name_plural': '网站更新内容'},
        ),
        migrations.AddField(
            model_name='development',
            name='story_time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='development',
            name='story_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='故事发布'),
        ),
        migrations.AlterField(
            model_name='development',
            name='story_title',
            field=models.TextField(blank=True, null=True, verbose_name='故事标题'),
        ),
    ]
