# Generated by Django 2.1 on 2019-11-12 07:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_auto_20191112_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='story_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='事件简要说明'),
        ),
        migrations.AlterField(
            model_name='development',
            name='story_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='故事标题'),
        ),
    ]
