# Generated by Django 2.1 on 2019-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_auto_20191112_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='story_time',
            field=models.DateTimeField(verbose_name='故事发布'),
        ),
        migrations.AlterField(
            model_name='development',
            name='story_time_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
