# Generated by Django 2.1 on 2019-11-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWebSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('introduce_text', models.TextField(verbose_name='个人简介')),
                ('introduce_image', models.ImageField(blank=True, null=True, upload_to='myself_photo/%Y%m%d/', verbose_name='个人头像')),
                ('skill', models.TextField(verbose_name='技能')),
                ('skill_open_time', models.DateTimeField(verbose_name='技能解锁时间')),
                ('skill_status', models.TextField(verbose_name='目前状态')),
            ],
            options={
                'verbose_name': '个人介绍',
                'verbose_name_plural': '个人介绍',
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='技能分类')),
            ],
            options={
                'verbose_name': '技能类别',
                'verbose_name_plural': '技能类别',
            },
        ),
        migrations.AddField(
            model_name='aboutwebskill',
            name='skill_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='about.SkillType', verbose_name='技能分类'),
        ),
    ]
