# Generated by Django 2.1 on 2019-11-26 07:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_models',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
    ]
