# Generated by Django 2.1 on 2019-11-06 06:52

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='点赞IP地址')),
                ('ip_loaction', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip归属地')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞列表',
            },
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('blog_photo', models.ImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='博客文章图片')),
                ('body', ckeditor.fields.RichTextField(verbose_name='文章标题')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='文章创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='文章更新时间')),
                ('article_view', models.PositiveIntegerField(default=0)),
                ('like', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='SeeMyWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='访问的IP地址')),
                ('visit_number', models.PositiveIntegerField(default=1, verbose_name='IP地址访问数量')),
                ('ip_loaction', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip归属地')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站访问量',
                'verbose_name_plural': '网站访问量',
            },
        ),
    ]
