# Generated by Django 2.1 on 2019-11-12 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191107_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetailView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='文章访问IP地址')),
                ('ip_loaction', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip归属地')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章访问IP统计',
                'verbose_name_plural': '文章访问IP统计',
            },
        ),
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'ordering': ('-create_time',), 'verbose_name': '博客文章分类', 'verbose_name_plural': '博客文章分类'},
        ),
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-create_time',), 'verbose_name': '博客文章', 'verbose_name_plural': '博客文章列表'},
        ),
        migrations.AddField(
            model_name='articledetailview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.ArticlePost', verbose_name='点赞文章'),
        ),
    ]
