# Generated by Django 2.1 on 2019-11-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191112_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailview',
            name='visit_number',
            field=models.PositiveIntegerField(default=1, verbose_name='IP地址访问数量'),
        ),
    ]
