# Generated by Django 2.1 on 2019-11-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_articledetailview_visit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetailview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.ArticlePost', verbose_name='其访问文章'),
        ),
    ]
